[theme]
primaryColor = "#bb5a38"
backgroundColor = "#f4f3ed"
secondaryBackgroundColor = "#ecebe3"
textColor = "#3d3a2a"
font = "sans serif"
showWidgetBorder = true
baseRadius = "0.6rem"

[server]
enableStaticServing = false
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
